---
- name: Install Composer
  shell: "curl -sS https://getcomposer.org/installer | php -- --install-dir={{ composer_install_dir }} --filename=composer"
  args:
    chdir: "{{ composer_install_dir }}"
    creates: composer
