---
- name: Write application vhost (API nodes only)
  become: true
  template:
    src: vhost.j2
    dest: /etc/nginx/sites-available/acme
    owner: root
    group: root
    mode: 0644

- name: Enable application vhost (API nodes only)
  become: true
  file:
    src: /etc/nginx/sites-available/acme
    dest: /etc/nginx/sites-enabled/acme
    state: link

- name: Restart PHP-FPM (API nodes only)
  become: true
  service:
    name: "php{{ php_version }}-fpm"
    state: restarted

- name: Restart Nginx (API nodes only)
  become: true
  service:
    name: nginx
    state: restarted
