all:
  children:
    backend:
      children:
        apis:
          hosts:
            api-1:
              ansible_host: 18.182.1.2
          vars:
            node_type: api
        workers:
          hosts:
            worker-1:
              ansible_host: 18.182.3.4
          vars:
            node_type: worker
        controllers:
          hosts:
            controller-1:
              ansible_host: 18.182.5.6
          vars:
            node_type: controller
      vars:
        ansible_python_interpreter: /usr/bin/python3
        ansible_connection: ssh
        ansible_port: 22
        ansible_user: ubuntu
        ansible_become_method: sudo
        ansible_become_user: root
        server_timezone: UTC
        server_locale: en_US.UTF-8
        server_log_level: error
        server_user: ubuntu
        server_user_group: ubuntu
        web_server_user: www-data
        web_server_user_group: www-data
        env: production
