---
- hosts: backend
  become: false
  vars:
    files_dir: "../files/{{ env }}"
  vars_files:
    - "../vars/{{ env }}/app.yml"
    - "../vars/{{ env }}/git.yml"
    - "../vars/{{ env }}/php.yml"
    - "../vars/{{ env }}/composer.yml"
  roles:
    - ../roles/pull
